name: 'Slack Notify Build'
description: 'Report GitHub Actions build status on Slack'
inputs:
  token:
    description: 'Github token'
    required: true
  run-id:
    description: 'Run ID'
    required: true
  run-number:
    description: 'Run number'
    required: true
outputs:
  message:
    description: 'Message payload'
runs:
  using: 'node20'
  main: 'dist/index.js'
