name: 'Slack Notify Build'
description: 'Report GitHub Actions build status on Slack'
inputs:
  slack-webhook-url:
    description: 'Slack webhook URL'
    required: true
runs:
  using: 'node12'
  main: 'index.js'
